[package]
name = "tree-sitter-canopy"
description = "Canopy grammar for tree-sitter"
version = "5.8.0"
authors = [
    "Harry Sarson <harry.sarson@hotmail.co.uk>",
    "Kolja Lampe <razzeee@gmail.com>"

]
readme = "README.md"
repository = "https://github.com/CanopyLang/tree-sitter-canopy"
keywords = ["incremental", "parsing", "tree-sitter", "canopy", "elm"]
categories = ["parser-implementations", "parsing", "text-editors"]
edition = "2021"
license = "MIT"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.3"
